# Generated by Django 4.1.5 on 2023-01-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phonenumber_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='status',
            new_name='number_status',
        ),
    ]
