# Generated by Django 4.1.5 on 2023-01-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_expiry_date_alter_subscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='status',
            new_name='subscription_status',
        ),
    ]
