# Generated by Django 4.1.5 on 2023-01-22 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_status_subscription_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
    ]
