# Generated by Django 4.1.5 on 2023-01-24 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 1, 24)),
        ),
    ]
